var namespaceestimatewjetsandqcdsameequationmethod =
[
    [ "EstimateWjetsAndQCDSameEquationMethod", "classestimatewjetsandqcdsameequationmethod_1_1EstimateWjetsAndQCDSameEquationMethod.html", "classestimatewjetsandqcdsameequationmethod_1_1EstimateWjetsAndQCDSameEquationMethod" ]
];