#!/bin/bash
# -*- coding: utf8 -*-

PEPIGNORE=W191,W391,E501,E101
CPPOPTIONS=$ANALYSIS_BASE/KITHiggsToTauTau/Analysis/scripts/astylerc
PATH=$PATH:/home/berger/sw/bin

# check for executables
which astyle > /dev/null|| echo "astyle is not installed. No C++ code check performed."
which pep8 > /dev/null || echo "pep8 is not installed. No python code check performed."

COUNT=0

for F in $(git diff --cached --name-status --diff-filter=ACMR)
do
	# check python
	if [[ "$F" =~ ^.+py$ ]]
	then
		which pep8 > /dev/null || continue
		pep8 -qq --ignore=$PEPIGNORE $F
		R=$?
		if [ "$R" != "0" ]
		then 
			if [ $COUNT -eq 0 ]; then echo "Please check these files for coding convention:"; fi
			pep8 -r --ignore=$PEPIGNORE --show-source $F
			let COUNT++
		fi
		
	fi

	# check C++
	if [[ "$F" =~ "^.+\.(cc|h|cpp|hxx|hh|c|C)$" ]]
	then
		which astyle > /dev/null || continue
		OUT="${F}.formatted"
		astyle --options=$CPPOPTIONS < $F > $OUT
		diff $F $OUT > /dev/null
		R=$?
		if [ "$R" != "0" ]
		then
			if [ $COUNT -eq 0 ]; then echo "Please check these files for coding convention:"; fi
			let COUNT++
			echo "meld $ANALYSIS_BASE/KITHiggsToTauTau/$F $ANALYSIS_BASE/KITHiggsToTauTau/$OUT"
		else
			rm $OUT
		fi
	fi
done

# do not commit bad commit (can be forced with git commit -n)
if [ "$COUNT" != "0" ]; then
	echo "Commit aborted due to bad code formatting."
	echo "Please fix and do a git add again! (-n forces commit)."
fi
exit $COUNT

