ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=4)

      DOUBLE PRECISION MDL_MT,MDL_MW,MDL_MZ,MDL_MTA,MDL_MB,MDL_MX2
     $ ,MDL_MX0,MDL_MX1

      COMMON/MASSES/ MDL_MT,MDL_MW,MDL_MZ,MDL_MTA,MDL_MB,MDL_MX2
     $ ,MDL_MX0,MDL_MX1


      DOUBLE PRECISION MDL_WW,MDL_WT,MDL_WZ,MDL_WX0,MDL_WX1,MDL_WX2

      COMMON/WIDTHS/ MDL_WW,MDL_WT,MDL_WZ,MDL_WX0,MDL_WX1,MDL_WX2


      DOUBLE COMPLEX GC_10, GC_64

      COMMON/COUPLINGS/ GC_10, GC_64

