#!/bin/bash

# GluGluH2JetsToTauTauM125CPmixingmaxmixJHU_RunIISpring16MiniAODv2_PUSpring16RAWAODSIM_13TeV_MINIAOD_unspecified
# GluGluH2JetsToTauTauM125CPmixingmaxmixJHU_RunIISummer16MiniAODv2_PUMoriond17_13TeV_MINIAOD_unspecified
# GluGluH2JetsToTauTauM125CPmixingpseudoscalarJHU_RunIISpring16MiniAODv2_PUSpring16RAWAODSIM_13TeV_MINIAOD_unspecified
# GluGluH2JetsToTauTauM125CPmixingpseudoscalarJHU_RunIISummer16MiniAODv2_PUMoriond17_13TeV_MINIAOD_unspecified
# GluGluH2JetsToTauTauM125CPmixingsmJHU_RunIISpring16MiniAODv2_PUSpring16RAWAODSIM_13TeV_MINIAOD_unspecified

# GluGluHToTauTauM125_RunIISummer16MiniAODv2_PUMoriond17_13TeV_MINIAOD_powheg
# GluGluHToTauTauM125_RunIISummer16MiniAODv2_PUMoriond17_13TeV_MINIAOD_powheg-pythia8

# GluGluToHToTauTauM125_RunIIFall15MiniAODv2_PU25nsData2015v1_13TeV_MINIAOD_amcatnlo-pythia8
# VBFHToTauTauM125_RunIISpring16MiniAODv2reHLT_PUSpring16RAWAODSIM_13TeV_MINIAOD_amcatnlo-pythia8
# VBFHToTauTauM125_RunIISummer16MiniAODv2_PUMoriond17_13TeV_MINIAOD_powheg-pythia8

higgsplot.py -m ELINE E ELINE E --legend 0.18 0.7 0.92 0.92 --y-lims 0 0.075 --legend-markers ELP --legend-cols 2 --formats png pdf --www jdphi -j HiggsAnalysis/KITHiggsToTauTau/data/plots/configs/control_plots/13TeV/default/jdphi.json --analysis-modules NormalizeToUnity -f "mt_nominal/ntuple et_nominal/ntuple tt_nominal/ntuple em_nominal/ntuple" --title "#tau#tau, #mu#tau, e#tau, e#mu (#alpha=0)" -d $1 -i GluGluToHToTauTauM125_RunIIFall15MiniAODv2_PU25nsData2015v1_13TeV_MINIAOD_amcatnlo-pythia8/*.root GluGluHToTauTauM125_RunIISummer16MiniAODv2_PUMoriond17_13TeV_MINIAOD_powheg-pythia8/*.root VBFHToTauTauM125_RunIISpring16MiniAODv2reHLT_PUSpring16RAWAODSIM_13TeV_MINIAOD_amcatnlo-pythia8/*.root VBFHToTauTauM125_RunIISummer16MiniAODv2_PUMoriond17_13TeV_MINIAOD_powheg-pythia8/*.root --labels "MadGraph (ggH, Fall15)" "Powheg (ggH, Summer16)" "MadGraph (VBF, Spring16)" "Powheg (VBF, Summer16)" -C kGreen kGreen kMagenta kMagenta --marker-styles 1 20 1 20 --filename MadGraph_Powheg

higgsplot.py -m ELINE E ELINE E ELINE E --legend 0.18 0.7 0.92 0.92 --y-lims 0 0.075 --legend-markers ELP --legend-cols 2 --formats png pdf --www jdphi -j HiggsAnalysis/KITHiggsToTauTau/data/plots/configs/control_plots/13TeV/default/jdphi.json --analysis-modules NormalizeToUnity -f "mt_nominal/ntuple et_nominal/ntuple tt_nominal/ntuple em_nominal/ntuple" --title "#tau#tau, #mu#tau, e#tau, e#mu" -d $1 -i GluGluToHToTauTauM125_RunIIFall15MiniAODv2_PU25nsData2015v1_13TeV_MINIAOD_amcatnlo-pythia8/*.root GluGluH2JetsToTauTauM125CPmixingsmJHU_RunIISpring16MiniAODv2_PUSpring16RAWAODSIM_13TeV_MINIAOD_unspecified/*.root GluGluToHToTauTauM125_RunIIFall15MiniAODv2_PU25nsData2015v1_13TeV_MINIAOD_amcatnlo-pythia8/*.root GluGluH2JetsToTauTauM125CPmixingmaxmixJHU_RunIISpring16MiniAODv2_PUSpring16RAWAODSIM_13TeV_MINIAOD_unspecified/*.root GluGluToHToTauTauM125_RunIIFall15MiniAODv2_PU25nsData2015v1_13TeV_MINIAOD_amcatnlo-pythia8/*.root GluGluH2JetsToTauTauM125CPmixingpseudoscalarJHU_RunIISpring16MiniAODv2_PUSpring16RAWAODSIM_13TeV_MINIAOD_unspecified/*.root -w "(jeta_1*jeta_2<0) * (mjj>500) * (abs(jdeta)>2.0) * (njets>1)" "(jeta_1*jeta_2<0) * (mjj>500) * (abs(jdeta)>2.0) * (njets>1)" "(jeta_1*jeta_2<0) * (mjj>500) * (abs(jdeta)>2.0) * (njets>1) * madGraphWeight050 * madGraphWeightInvSample * ((madGraphWeight050 * madGraphWeightInvSample) < 20)" "(jeta_1*jeta_2<0) * (mjj>500) * (abs(jdeta)>2.0) * (njets>1)" "(jeta_1*jeta_2<0) * (mjj>500) * (abs(jdeta)>2.0) * (njets>1) * madGraphWeight100 * madGraphWeightInvSample * ((madGraphWeight100 * madGraphWeightInvSample) < 20)" "(jeta_1*jeta_2<0) * (mjj>500) * (abs(jdeta)>2.0) * (njets>1)" --labels "MadGraph (#alpha=0, Fall15)" "JHU (#alpha=0, Spring16)" "MadGraph (#alpha=#pi/4, Fall15)" "JHU (#alpha=#pi/4, Spring16)" "MadGraph (#alpha=#pi/2, Fall15)" "JHU (#alpha=#pi/2, Spring16)" -C kGreen kGreen kBlue kBlue kRed kRed --marker-styles 1 20 1 20 1 20 --filename MadGraph_JHU

higgsplot.py -m ELINE --legend 0.18 0.7 0.92 0.92 --y-lims 0 0.075 --legend-markers ELP --legend-cols 2 --formats png pdf --www jdphi -j HiggsAnalysis/KITHiggsToTauTau/data/plots/configs/control_plots/13TeV/default/jdphi.json --analysis-modules NormalizeToUnity -f "mt_nominal/ntuple et_nominal/ntuple tt_nominal/ntuple em_nominal/ntuple" --title "#tau#tau, #mu#tau, e#tau, e#mu (Fall15)" -d $1 -i GluGluToHToTauTauM125_RunIIFall15MiniAODv2_PU25nsData2015v1_13TeV_MINIAOD_amcatnlo-pythia8/*.root -w "(jeta_1*jeta_2<0) * (mjj>500) * (abs(jdeta)>2.0) * (njets>1)" "(jeta_1*jeta_2<0) * (mjj>500) * (abs(jdeta)>2.0) * (njets>1) * madGraphWeight050 * madGraphWeightInvSample * ((madGraphWeight050 * madGraphWeightInvSample) < 20)" "(jeta_1*jeta_2<0) * (mjj>500) * (abs(jdeta)>2.0) * (njets>1) * madGraphWeight100 * madGraphWeightInvSample * ((madGraphWeight100 * madGraphWeightInvSample) < 20)" --labels "MadGraph (#alpha=0)" "MadGraph (#alpha=#pi/4)" "MadGraph (#alpha=#pi/2)" -C kGreen kBlue kRed --filename MadGraph

higgsplot.py -m E ELINE --legend 0.18 0.7 0.92 0.92 --y-lims 0 0.075 --legend-markers ELP --legend-cols 2 --formats png pdf --www jdphi -j HiggsAnalysis/KITHiggsToTauTau/data/plots/configs/control_plots/13TeV/default/jdphi.json --analysis-modules NormalizeToUnity -f "mt_nominal/ntuple et_nominal/ntuple tt_nominal/ntuple em_nominal/ntuple" --title "#tau#tau, #mu#tau, e#tau, e#mu (#alpha=0, Summer16)" -d $1 -i GluGluHToTauTauM125_RunIISummer16MiniAODv2_PUMoriond17_13TeV_MINIAOD_powheg-pythia8/*.root GluGluHToTauTauM125_RunIISummer16MiniAODv2_PUMoriond17_13TeV_MINIAOD_powheg/*.root --labels "Powheg+Ptyhia" "Powheg+Herwig" -C kGreen kGreen --marker-styles 20 1 --filename Powheg

higgsplot.py -m ELINE --legend 0.18 0.7 0.92 0.92 --y-lims 0 0.075 --legend-markers ELP --legend-cols 2 --formats png pdf --www jdphi -j HiggsAnalysis/KITHiggsToTauTau/data/plots/configs/control_plots/13TeV/default/jdphi.json --analysis-modules NormalizeToUnity -f "mt_nominal/ntuple et_nominal/ntuple tt_nominal/ntuple em_nominal/ntuple" --title "#tau#tau, #mu#tau, e#tau, e#mu (Spring16)" -d $1 -i GluGluH2JetsToTauTauM125CPmixingsmJHU_RunIISpring16MiniAODv2_PUSpring16RAWAODSIM_13TeV_MINIAOD_unspecified/*.root GluGluH2JetsToTauTauM125CPmixingmaxmixJHU_RunIISpring16MiniAODv2_PUSpring16RAWAODSIM_13TeV_MINIAOD_unspecified/*.root GluGluH2JetsToTauTauM125CPmixingpseudoscalarJHU_RunIISpring16MiniAODv2_PUSpring16RAWAODSIM_13TeV_MINIAOD_unspecified/*.root --labels "JHU (#alpha=0)" "JHU (#alpha=#pi/4)" "JHU (#alpha=#pi/2)" -C kGreen kBlue kRed --filename JHU_Spring16

higgsplot.py -m ELINE --legend 0.18 0.7 0.92 0.92 --y-lims 0 0.075 --legend-markers ELP --legend-cols 2 --formats png pdf --www jdphi -j HiggsAnalysis/KITHiggsToTauTau/data/plots/configs/control_plots/13TeV/default/jdphi.json --analysis-modules NormalizeToUnity -f "tt_nominal/ntuple" --title "#tau#tau (Spring16)" -d $1 -i GluGluH2JetsToTauTauM125CPmixingsmJHU_RunIISpring16MiniAODv2_PUSpring16RAWAODSIM_13TeV_MINIAOD_unspecified/*.root GluGluH2JetsToTauTauM125CPmixingmaxmixJHU_RunIISpring16MiniAODv2_PUSpring16RAWAODSIM_13TeV_MINIAOD_unspecified/*.root GluGluH2JetsToTauTauM125CPmixingpseudoscalarJHU_RunIISpring16MiniAODv2_PUSpring16RAWAODSIM_13TeV_MINIAOD_unspecified/*.root --labels "JHU (#alpha=0)" "JHU (#alpha=#pi/4)" "JHU (#alpha=#pi/2)" -C kGreen kBlue kRed --filename JHU_Spring16_tt

higgsplot.py -m ELINE --legend 0.18 0.7 0.92 0.92 --y-lims 0 0.075 --legend-markers ELP --legend-cols 2 --formats png pdf --www jdphi -j HiggsAnalysis/KITHiggsToTauTau/data/plots/configs/control_plots/13TeV/default/jdphi.json --analysis-modules NormalizeToUnity -f "mt_nominal/ntuple et_nominal/ntuple tt_nominal/ntuple em_nominal/ntuple" --title "#tau#tau, #mu#tau, e#tau, e#mu (Summer16)" -d $1 -i GluGluH2JetsToTauTauM125CPmixingmaxmixJHU_RunIISummer16MiniAODv2_PUMoriond17_13TeV_MINIAOD_unspecified/*.root GluGluH2JetsToTauTauM125CPmixingpseudoscalarJHU_RunIISummer16MiniAODv2_PUMoriond17_13TeV_MINIAOD_unspecified/*.root --labels "JHU (#alpha=#pi/4)" "JHU (#alpha=#pi/2)" -C kBlue kRed --filename JHU_Summer16

higgsplot.py -m E E E ELINE ELINE --legend 0.18 0.7 0.92 0.92 --y-lims 0 0.075 --legend-markers ELP --legend-cols 2 --formats png pdf --www jdphi -j HiggsAnalysis/KITHiggsToTauTau/data/plots/configs/control_plots/13TeV/default/jdphi.json --analysis-modules NormalizeToUnity -f "mt_nominal/ntuple et_nominal/ntuple tt_nominal/ntuple em_nominal/ntuple" --title "#tau#tau, #mu#tau, e#tau, e#mu" -d $1 -i GluGluH2JetsToTauTauM125CPmixingsmJHU_RunIISpring16MiniAODv2_PUSpring16RAWAODSIM_13TeV_MINIAOD_unspecified/*.root GluGluH2JetsToTauTauM125CPmixingmaxmixJHU_RunIISpring16MiniAODv2_PUSpring16RAWAODSIM_13TeV_MINIAOD_unspecified/*.root GluGluH2JetsToTauTauM125CPmixingpseudoscalarJHU_RunIISpring16MiniAODv2_PUSpring16RAWAODSIM_13TeV_MINIAOD_unspecified/*.root GluGluH2JetsToTauTauM125CPmixingmaxmixJHU_RunIISummer16MiniAODv2_PUMoriond17_13TeV_MINIAOD_unspecified/*.root GluGluH2JetsToTauTauM125CPmixingpseudoscalarJHU_RunIISummer16MiniAODv2_PUMoriond17_13TeV_MINIAOD_unspecified/*.root --labels "JHU (#alpha=0, Spring16)" "JHU (#alpha=#pi/4, Spring16)" "JHU (#alpha=#pi/2, Spring16)" "JHU (#alpha=#pi/4, Summer16)" "JHU (#alpha=#pi/2, Summer16)" -C kGreen kBlue kRed kBlue kRed --marker-styles 20 20 20 1 1 --filename JHU

higgsplot.py -m E E E ELINE ELINE --legend 0.18 0.7 0.92 0.92 --y-lims 0 0.075 --legend-markers ELP --legend-cols 2 --formats png pdf --www jdphi -j HiggsAnalysis/KITHiggsToTauTau/data/plots/configs/control_plots/13TeV/default/jdphi.json --analysis-modules NormalizeToUnity -f "tt_nominal/ntuple" --title "#tau#tau" -d $1 -i GluGluH2JetsToTauTauM125CPmixingsmJHU_RunIISpring16MiniAODv2_PUSpring16RAWAODSIM_13TeV_MINIAOD_unspecified/*.root GluGluH2JetsToTauTauM125CPmixingmaxmixJHU_RunIISpring16MiniAODv2_PUSpring16RAWAODSIM_13TeV_MINIAOD_unspecified/*.root GluGluH2JetsToTauTauM125CPmixingpseudoscalarJHU_RunIISpring16MiniAODv2_PUSpring16RAWAODSIM_13TeV_MINIAOD_unspecified/*.root GluGluH2JetsToTauTauM125CPmixingmaxmixJHU_RunIISummer16MiniAODv2_PUMoriond17_13TeV_MINIAOD_unspecified/*.root GluGluH2JetsToTauTauM125CPmixingpseudoscalarJHU_RunIISummer16MiniAODv2_PUMoriond17_13TeV_MINIAOD_unspecified/*.root --labels "JHU (#alpha=0, Spring16)" "JHU (#alpha=#pi/4, Spring16)" "JHU (#alpha=#pi/2, Spring16)" "JHU (#alpha=#pi/4, Summer16)" "JHU (#alpha=#pi/2, Summer16)" -C kGreen kBlue kRed kBlue kRed --marker-styles 20 20 20 1 1 --filename JHU_tt

