#!/bin/sh
# call with Artus project directory containing ggH (Powheg) samples

makePlots_controlPlots.py -n 4 --www svfit -i $1 -s ggh -c mt et tt em -x "(svfitLV.Pt()-genBosonLV.Pt())/genBosonLV.Pt()" -w "(svfitLV.mass()<5000)*(genBosonLV.mass()<5000)" -a " --x-bins 51,-1,1 --x-label \"#left(p_{T}^{reco}(#tau#tau) - p_{T}^{gen}(#tau#tau)#right) / p_{T}^{gen}(#tau#tau)\" --formats pdf png --y-label \"arb. units\"" --analysis-modules NormalizeToUnity
makePlots_controlPlots.py -n 4 --www svfit -i $1 -s ggh -c mt et tt em -x "(svfitLV.Eta()-genBosonLV.Eta())/genBosonLV.Eta()" -w "(svfitLV.mass()<5000)*(genBosonLV.mass()<5000)" -a " --x-bins 51,-1,1 --x-label \"#left(#eta^{reco}(#tau#tau) - #eta^{gen}(#tau#tau)#right) / #eta^{gen}(#tau#tau)\" --formats pdf png --y-label \"arb. units\"" --analysis-modules NormalizeToUnity
makePlots_controlPlots.py -n 4 --www svfit -i $1 -s ggh -c mt et tt em -x "(svfitLV.Phi()-genBosonLV.Phi())/genBosonLV.Phi()" -w "(svfitLV.mass()<5000)*(genBosonLV.mass()<5000)" -a " --x-bins 51,-1,1 --x-label \"#left(#phi^{reco}(#tau#tau) - #phi^{gen}(#tau#tau)#right) / #phi^{gen}(#tau#tau)\" --formats pdf png --y-label \"arb. units\"" --analysis-modules NormalizeToUnity
makePlots_controlPlots.py -n 4 --www svfit -i $1 -s ggh -c mt et tt em -x "(svfitLV.mass()-genBosonLV.mass())/genBosonLV.mass()" -w "(svfitLV.mass()<5000)*(genBosonLV.mass()<5000)" -a " --x-bins 51,-1,1 --x-label \"#left(m^{reco}(#tau#tau) - m^{gen}(#tau#tau)#right) / m^{gen}(#tau#tau)\" --formats pdf png --y-label \"arb. units\"" --analysis-modules NormalizeToUnity
makePlots_controlPlots.py -n 4 --www svfit -i $1 -s ggh -c mt et tt em -x "(svfitLV.E()-genBosonLV.E())/genBosonLV.E()" -w "(svfitLV.mass()<5000)*(genBosonLV.mass()<5000)" -a " --x-bins 51,-1,1 --x-label \"#left(E^{reco}(#tau#tau) - E^{gen}(#tau#tau)#right) / E^{gen}(#tau#tau)\" --formats pdf png --y-label \"arb. units\"" --analysis-modules NormalizeToUnity


makePlots_controlPlots.py -n 4 --www svfit -i $1 -s ggh -c mt et tt em -x "(svfitTau1LV.Pt()-genBosonTau1LV.Pt())/genBosonTau1LV.Pt()" -w "(svfitTau1LV.mass()<5000)*(genBosonTau1LV.mass()<5000)" -a " --x-bins 51,-1,1 --x-label \"#left(p_{T}^{reco}(#tau_{1}) - p_{T}^{gen}(#tau_{1})#right) / p_{T}^{gen}(#tau_{1})\" --formats pdf png --y-label \"arb. units\"" --analysis-modules NormalizeToUnity
makePlots_controlPlots.py -n 4 --www svfit -i $1 -s ggh -c mt et tt em -x "(svfitTau1LV.Eta()-genBosonTau1LV.Eta())/genBosonTau1LV.Eta()" -w "(svfitTau1LV.mass()<5000)*(genBosonTau1LV.mass()<5000)" -a " --x-bins 51,-1,1 --x-label \"#left(#eta^{reco}(#tau_{1}) - #eta^{gen}(#tau_{1})#right) / #eta^{gen}(#tau_{1})\" --formats pdf png --y-label \"arb. units\"" --analysis-modules NormalizeToUnity
makePlots_controlPlots.py -n 4 --www svfit -i $1 -s ggh -c mt et tt em -x "(svfitTau1LV.Phi()-genBosonTau1LV.Phi())/genBosonTau1LV.Phi()" -w "(svfitTau1LV.mass()<5000)*(genBosonTau1LV.mass()<5000)" -a " --x-bins 51,-1,1 --x-label \"#left(#phi^{reco}(#tau_{1}) - #phi^{gen}(#tau_{1})#right) / #phi^{gen}(#tau_{1})\" --formats pdf png --y-label \"arb. units\"" --analysis-modules NormalizeToUnity
makePlots_controlPlots.py -n 4 --www svfit -i $1 -s ggh -c mt et tt em -x "(svfitTau1LV.mass()-genBosonTau1LV.mass())/genBosonTau1LV.mass()" -w "(svfitTau1LV.mass()<5000)*(genBosonTau1LV.mass()<5000)" -a " --x-bins 51,-1,1 --x-label \"#left(m^{reco}(#tau_{1}) - m^{gen}(#tau_{1})#right) / m^{gen}(#tau_{1})\" --formats pdf png --y-label \"arb. units\"" --analysis-modules NormalizeToUnity
makePlots_controlPlots.py -n 4 --www svfit -i $1 -s ggh -c mt et tt em -x "(svfitTau1LV.E()-genBosonTau1LV.E())/genBosonTau1LV.E()" -w "(svfitTau1LV.mass()<5000)*(genBosonTau1LV.mass()<5000)" -a " --x-bins 51,-1,1 --x-label \"#left(E^{reco}(#tau_{1}) - E^{gen}(#tau_{1})#right) / E^{gen}(#tau_{1})\" --formats pdf png --y-label \"arb. units\"" --analysis-modules NormalizeToUnity


makePlots_controlPlots.py -n 4 --www svfit -i $1 -s ggh -c mt et tt em -x "(svfitTau2LV.Pt()-genBosonTau2LV.Pt())/genBosonTau2LV.Pt()" -w "(svfitTau2LV.mass()<5000)*(genBosonTau2LV.mass()<5000)" -a " --x-bins 51,-1,1 --x-label \"#left(p_{T}^{reco}(#tau_{2}) - p_{T}^{gen}(#tau_{2})#right) / p_{T}^{gen}(#tau_{2})\" --formats pdf png --y-label \"arb. units\"" --analysis-modules NormalizeToUnity
makePlots_controlPlots.py -n 4 --www svfit -i $1 -s ggh -c mt et tt em -x "(svfitTau2LV.Eta()-genBosonTau2LV.Eta())/genBosonTau2LV.Eta()" -w "(svfitTau2LV.mass()<5000)*(genBosonTau2LV.mass()<5000)" -a " --x-bins 51,-1,1 --x-label \"#left(#eta^{reco}(#tau_{2}) - #eta^{gen}(#tau_{2})#right) / #eta^{gen}(#tau_{2})\" --formats pdf png --y-label \"arb. units\"" --analysis-modules NormalizeToUnity
makePlots_controlPlots.py -n 4 --www svfit -i $1 -s ggh -c mt et tt em -x "(svfitTau2LV.Phi()-genBosonTau2LV.Phi())/genBosonTau2LV.Phi()" -w "(svfitTau2LV.mass()<5000)*(genBosonTau2LV.mass()<5000)" -a " --x-bins 51,-1,1 --x-label \"#left(#phi^{reco}(#tau_{2}) - #phi^{gen}(#tau_{2})#right) / #phi^{gen}(#tau_{2})\" --formats pdf png --y-label \"arb. units\"" --analysis-modules NormalizeToUnity
makePlots_controlPlots.py -n 4 --www svfit -i $1 -s ggh -c mt et tt em -x "(svfitTau2LV.mass()-genBosonTau2LV.mass())/genBosonTau2LV.mass()" -w "(svfitTau2LV.mass()<5000)*(genBosonTau2LV.mass()<5000)" -a " --x-bins 51,-1,1 --x-label \"#left(m^{reco}(#tau_{2}) - m^{gen}(#tau_{2})#right) / m^{gen}(#tau_{2})\" --formats pdf png --y-label \"arb. units\"" --analysis-modules NormalizeToUnity
makePlots_controlPlots.py -n 4 --www svfit -i $1 -s ggh -c mt et tt em -x "(svfitTau2LV.E()-genBosonTau2LV.E())/genBosonTau2LV.E()" -w "(svfitTau2LV.mass()<5000)*(genBosonTau2LV.mass()<5000)" -a " --x-bins 51,-1,1 --x-label \"#left(E^{reco}(#tau_{2}) - E^{gen}(#tau_{2})#right) / E^{gen}(#tau_{2})\" --formats pdf png --y-label \"arb. units\"" --analysis-modules NormalizeToUnity



makePlots_controlPlots.py -n 4 --www svfit -i $1 -s ggh -c mt et tt em -x "svfitLV.Pt()/genBosonLV.Pt()" -w "(svfitLV.mass()<5000)*(genBosonLV.mass()<5000)" -a " --x-bins 51,0,2 --x-label \"p_{T}^{reco}(#tau#tau) / p_{T}^{gen}(#tau#tau)\" --formats pdf png --y-label \"arb. units\"" --analysis-modules NormalizeToUnity
makePlots_controlPlots.py -n 4 --www svfit -i $1 -s ggh -c mt et tt em -x "svfitLV.Eta()/genBosonLV.Eta()" -w "(svfitLV.mass()<5000)*(genBosonLV.mass()<5000)" -a " --x-bins 51,0,2 --x-label \"#eta^{reco}(#tau#tau) / #eta^{gen}(#tau#tau)\" --formats pdf png --y-label \"arb. units\"" --analysis-modules NormalizeToUnity
makePlots_controlPlots.py -n 4 --www svfit -i $1 -s ggh -c mt et tt em -x "svfitLV.Phi()/genBosonLV.Phi()" -w "(svfitLV.mass()<5000)*(genBosonLV.mass()<5000)" -a " --x-bins 51,0,2 --x-label \"#phi^{reco}(#tau#tau) / #phi^{gen}(#tau#tau)\" --formats pdf png --y-label \"arb. units\"" --analysis-modules NormalizeToUnity
makePlots_controlPlots.py -n 4 --www svfit -i $1 -s ggh -c mt et tt em -x "svfitLV.mass()/genBosonLV.mass()" -w "(svfitLV.mass()<5000)*(genBosonLV.mass()<5000)" -a " --x-bins 51,0,2 --x-label \"m^{reco}(#tau#tau) / m^{gen}(#tau#tau)\" --formats pdf png --y-label \"arb. units\"" --analysis-modules NormalizeToUnity
makePlots_controlPlots.py -n 4 --www svfit -i $1 -s ggh -c mt et tt em -x "svfitLV.E()/genBosonLV.E()" -w "(svfitLV.mass()<5000)*(genBosonLV.mass()<5000)" -a " --x-bins 51,0,2 --x-label \"E^{reco}(#tau#tau) / E^{gen}(#tau#tau)\" --formats pdf png --y-label \"arb. units\"" --analysis-modules NormalizeToUnity


makePlots_controlPlots.py -n 4 --www svfit -i $1 -s ggh -c mt et tt em -x "svfitTau1LV.Pt()/genBosonTau1LV.Pt()" -w "(svfitTau1LV.mass()<5000)*(genBosonTau1LV.mass()<5000)" -a " --x-bins 51,0,2 --x-label \"p_{T}^{reco}(#tau_{1}) / p_{T}^{gen}(#tau_{1})\" --formats pdf png --y-label \"arb. units\"" --analysis-modules NormalizeToUnity
makePlots_controlPlots.py -n 4 --www svfit -i $1 -s ggh -c mt et tt em -x "svfitTau1LV.Eta()/genBosonTau1LV.Eta()" -w "(svfitTau1LV.mass()<5000)*(genBosonTau1LV.mass()<5000)" -a " --x-bins 51,0,2 --x-label \"#eta^{reco}(#tau_{1}) / #eta^{gen}(#tau_{1})\" --formats pdf png --y-label \"arb. units\"" --analysis-modules NormalizeToUnity
makePlots_controlPlots.py -n 4 --www svfit -i $1 -s ggh -c mt et tt em -x "svfitTau1LV.Phi()/genBosonTau1LV.Phi()" -w "(svfitTau1LV.mass()<5000)*(genBosonTau1LV.mass()<5000)" -a " --x-bins 51,0,2 --x-label \"#phi^{reco}(#tau_{1}) / #phi^{gen}(#tau_{1})\" --formats pdf png --y-label \"arb. units\"" --analysis-modules NormalizeToUnity
makePlots_controlPlots.py -n 4 --www svfit -i $1 -s ggh -c mt et tt em -x "svfitTau1LV.mass()/genBosonTau1LV.mass()" -w "(svfitTau1LV.mass()<5000)*(genBosonTau1LV.mass()<5000)" -a " --x-bins 51,0,2 --x-label \"m^{reco}(#tau_{1}) / m^{gen}(#tau_{1})\" --formats pdf png --y-label \"arb. units\"" --analysis-modules NormalizeToUnity
makePlots_controlPlots.py -n 4 --www svfit -i $1 -s ggh -c mt et tt em -x "svfitTau1LV.E()/genBosonTau1LV.E()" -w "(svfitTau1LV.mass()<5000)*(genBosonTau1LV.mass()<5000)" -a " --x-bins 51,0,2 --x-label \"E^{reco}(#tau_{1}) / E^{gen}(#tau_{1})\" --formats pdf png --y-label \"arb. units\"" --analysis-modules NormalizeToUnity


makePlots_controlPlots.py -n 4 --www svfit -i $1 -s ggh -c mt et tt em -x "svfitTau2LV.Pt()/genBosonTau2LV.Pt()" -w "(svfitTau2LV.mass()<5000)*(genBosonTau2LV.mass()<5000)" -a " --x-bins 51,0,2 --x-label \"p_{T}^{reco}(#tau_{2}) / p_{T}^{gen}(#tau_{2})\" --formats pdf png --y-label \"arb. units\"" --analysis-modules NormalizeToUnity
makePlots_controlPlots.py -n 4 --www svfit -i $1 -s ggh -c mt et tt em -x "svfitTau2LV.Eta()/genBosonTau2LV.Eta()" -w "(svfitTau2LV.mass()<5000)*(genBosonTau2LV.mass()<5000)" -a " --x-bins 51,0,2 --x-label \"#eta^{reco}(#tau_{2}) / #eta^{gen}(#tau_{2})\" --formats pdf png --y-label \"arb. units\"" --analysis-modules NormalizeToUnity
makePlots_controlPlots.py -n 4 --www svfit -i $1 -s ggh -c mt et tt em -x "svfitTau2LV.Phi()/genBosonTau2LV.Phi()" -w "(svfitTau2LV.mass()<5000)*(genBosonTau2LV.mass()<5000)" -a " --x-bins 51,0,2 --x-label \"#phi^{reco}(#tau_{2}) / #phi^{gen}(#tau_{2})\" --formats pdf png --y-label \"arb. units\"" --analysis-modules NormalizeToUnity
makePlots_controlPlots.py -n 4 --www svfit -i $1 -s ggh -c mt et tt em -x "svfitTau2LV.mass()/genBosonTau2LV.mass()" -w "(svfitTau2LV.mass()<5000)*(genBosonTau2LV.mass()<5000)" -a " --x-bins 51,0,2 --x-label \"m^{reco}(#tau_{2}) / m^{gen}(#tau_{2})\" --formats pdf png --y-label \"arb. units\"" --analysis-modules NormalizeToUnity
makePlots_controlPlots.py -n 4 --www svfit -i $1 -s ggh -c mt et tt em -x "svfitTau2LV.E()/genBosonTau2LV.E()" -w "(svfitTau2LV.mass()<5000)*(genBosonTau2LV.mass()<5000)" -a " --x-bins 51,0,2 --x-label \"E^{reco}(#tau_{2}) / E^{gen}(#tau_{2})\" --formats pdf png --y-label \"arb. units\"" --analysis-modules NormalizeToUnity

