#!/bin/sh

# EM

higgsplot.py --no-cache --legend 0.22 0.75 0.9 0.9 --legend-markers LP --legend-cols 4 --x-label "Average Polarisation #LTP_{#tau}#GT" --y-label "Likelihood -2#Deltaln L" -f limit -x pol -y "2*deltaNLL" --tree-draw-options TGraph --analysis-modules LikelihoodScan -m LP L L L --marker-sizes 0.5 --line-styles 1 1 2 3 --formats pdf png --www taupol/likelihood_scans/asimov/em --title "e#mu, r floating" --filename pol_combined -i plots/2018-05-22_ztt_polarisation_datacards_mt_et_em_leg1_tt_inclusive/datacards/individual/em/1031/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2/datacards/individual/em/1032/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_em_combined/datacards/individual/em/1060/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_em_leg1_tt_inclusive_m_vis/datacards/individual/em/1031/higgsCombine.pol.MultiDimFit.mH0.root -C 2 2 2 2 3 3 3 3 4 4 4 4 6 6 6 6 --y-lims 0 10 --x-lims -1 1 --labels "#bar{#omega}(e)" "" "" "" "#bar{#omega}(#mu)" "" "" "" "#bar{#Omega}(e,#mu)" "" "" "" "m_{vis}(e,#mu)" "" "" "" &

higgsplot.py --no-cache --legend 0.22 0.75 0.9 0.9 --legend-markers LP --legend-cols 4 --x-label "Average Polarisation #LTP_{#tau}#GT" --y-label "Likelihood -2#Deltaln L" -f limit -x pol -y "2*deltaNLL" --tree-draw-options TGraph --analysis-modules LikelihoodScan -m LP L L L --marker-sizes 0.5 --line-styles 1 1 2 3 --formats pdf png --www taupol/likelihood_scans/asimov/em --title "e#mu, r=1 fixed" --filename pol_r1_combined -i plots/2018-05-22_ztt_polarisation_datacards_mt_et_em_leg1_tt_inclusive/datacards/individual/em/1031/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2/datacards/individual/em/1032/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_em_combined/datacards/individual/em/1060/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_em_leg1_tt_inclusive_m_vis/datacards/individual/em/1031/higgsCombine.pol_r1.MultiDimFit.mH0.root -C 2 2 2 2 3 3 3 3 4 4 4 4 6 6 6 6 --y-lims 0 10 --x-lims -1 1 --labels "#bar{#omega}(e)" "" "" "" "#bar{#omega}(#mu)" "" "" "" "#bar{#Omega}(e,#mu)" "" "" "" "m_{vis}(e,#mu)" "" "" "" &

higgsplot.py --no-cache --legend 0.22 0.75 0.9 0.9 --legend-markers LP --legend-cols 4 --x-label "Average Polarisation #LTP_{#tau}#GT" --y-label "Likelihood -2#Deltaln L" -f limit -x pol -y "2*deltaNLL" --tree-draw-options TGraph --analysis-modules LikelihoodScan -m LP L L L --marker-sizes 0.5 --line-styles 1 1 2 3 --formats pdf png --www taupol/likelihood_scans/asimov/em --title "e#mu, m_{vis}(e,#mu)" --filename pol_combined_r_comparison -i plots/2018-05-22_ztt_polarisation_datacards_mt_et_em_leg1_tt_inclusive_m_vis/datacards/individual/em/1031/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_em_leg1_tt_inclusive_m_vis/datacards/individual/em/1031/higgsCombine.pol_r1.MultiDimFit.mH0.root -C 2 2 2 2 3 3 3 3 --y-lims 0 10 --x-lims -1 1 --labels "r floating" "" "" "" "r=1 fixed" "" "" "" &

## zoomed

higgsplot.py --no-cache --legend 0.22 0.75 0.9 0.9 --legend-markers LP --legend-cols 4 --x-label "Average Polarisation #LTP_{#tau}#GT" --y-label "Likelihood -2#Deltaln L" -f limit -x pol -y "2*deltaNLL" --tree-draw-options TGraph --analysis-modules LikelihoodScan -m LP L L L --marker-sizes 0.5 --line-styles 1 1 2 3 --formats pdf png --www taupol/likelihood_scans/asimov/em --title "e#mu, r floating" --filename pol_combined_zoom -i plots/2018-05-22_ztt_polarisation_datacards_mt_et_em_leg1_tt_inclusive/datacards/individual/em/1031/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2/datacards/individual/em/1032/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_em_combined/datacards/individual/em/1060/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_em_leg1_tt_inclusive_m_vis/datacards/individual/em/1031/higgsCombine.pol.MultiDimFit.mH0.root -C 2 2 2 2 3 3 3 3 4 4 4 4 6 6 6 6 --y-lims 0 10 --x-lims -0.3 0.0 --labels "#bar{#omega}(e)" "" "" "" "#bar{#omega}(#mu)" "" "" "" "#bar{#Omega}(e,#mu)" "" "" "" "m_{vis}(e,#mu)" "" "" "" &

higgsplot.py --no-cache --legend 0.22 0.75 0.9 0.9 --legend-markers LP --legend-cols 4 --x-label "Average Polarisation #LTP_{#tau}#GT" --y-label "Likelihood -2#Deltaln L" -f limit -x pol -y "2*deltaNLL" --tree-draw-options TGraph --analysis-modules LikelihoodScan -m LP L L L --marker-sizes 0.5 --line-styles 1 1 2 3 --formats pdf png --www taupol/likelihood_scans/asimov/em --title "e#mu, r=1 fixed" --filename pol_r1_combined_zoom -i plots/2018-05-22_ztt_polarisation_datacards_mt_et_em_leg1_tt_inclusive/datacards/individual/em/1031/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2/datacards/individual/em/1032/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_em_combined/datacards/individual/em/1060/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_em_leg1_tt_inclusive_m_vis/datacards/individual/em/1031/higgsCombine.pol_r1.MultiDimFit.mH0.root -C 2 2 2 2 3 3 3 3 4 4 4 4 6 6 6 6 --y-lims 0 10 --x-lims -0.3 0.0 --labels "#bar{#omega}(e)" "" "" "" "#bar{#omega}(#mu)" "" "" "" "#bar{#Omega}(e,#mu)" "" "" "" "m_{vis}(e,#mu)" "" "" "" &

higgsplot.py --no-cache --legend 0.22 0.75 0.9 0.9 --legend-markers LP --legend-cols 4 --x-label "Average Polarisation #LTP_{#tau}#GT" --y-label "Likelihood -2#Deltaln L" -f limit -x pol -y "2*deltaNLL" --tree-draw-options TGraph --analysis-modules LikelihoodScan -m LP L L L --marker-sizes 0.5 --line-styles 1 1 2 3 --formats pdf png --www taupol/likelihood_scans/asimov/em --title "e#mu, m_{vis}(e,#mu)" --filename pol_combined_r_comparison_zoom -i plots/2018-05-22_ztt_polarisation_datacards_mt_et_em_leg1_tt_inclusive_m_vis/datacards/individual/em/1031/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_em_leg1_tt_inclusive_m_vis/datacards/individual/em/1031/higgsCombine.pol_r1.MultiDimFit.mH0.root -C 2 2 2 2 3 3 3 3 --y-lims 0 10 --x-lims -0.3 0.0 --labels "r floating" "" "" "" "r=1 fixed" "" "" "" &



# MT

higgsplot.py --no-cache --legend 0.22 0.7 0.9 0.9 --legend-markers LP --legend-cols 3 --x-label "Average Polarisation #LTP_{#tau}#GT" --y-label "Likelihood -2#Deltaln L" -f limit -x pol -y "2*deltaNLL" --tree-draw-options TGraph --analysis-modules LikelihoodScan -m LP L L L --marker-sizes 0.5 --line-styles 1 1 2 3 --formats pdf png --www taupol/likelihood_scans/asimov/mt --title "#mu#tau_{h}, r floating" --filename pol_combined -i plots/2018-05-22_ztt_polarisation_datacards_mt_et_em_leg1_tt_inclusive/datacards/individual/mt/1031/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_em_leg1_tt_inclusive_m_vis/datacards/individual/mt/1031/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_em_combined/datacards/channel/mt/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2/datacards/channel/mt/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2_m_vis/datacards/channel/mt/higgsCombine.pol.MultiDimFit.mH0.root -C 2 2 2 2 3 3 3 3 4 4 4 4 6 6 6 6 7 7 7 7 --y-lims 0 100 --x-lims -1 1 --labels "#bar{#omega}(#mu)" "" "" "" "#bar{#omega}(a_{1}/#rho/#pi)" "" "" "" "#bar{#Omega}(#mu,a_{1}/#rho/#pi)" "" "" "" "m_{vis}(#mu,#tau_{h})" "" "" "" "m_{vis}(#mu,a_{1}/#rho/#pi)" "" "" "" &

higgsplot.py --no-cache --legend 0.22 0.7 0.9 0.9 --legend-markers LP --legend-cols 3 --x-label "Average Polarisation #LTP_{#tau}#GT" --y-label "Likelihood -2#Deltaln L" -f limit -x pol -y "2*deltaNLL" --tree-draw-options TGraph --analysis-modules LikelihoodScan -m LP L L L --marker-sizes 0.5 --line-styles 1 1 2 3 --formats pdf png --www taupol/likelihood_scans/asimov/mt --title "#mu#tau_{h}, r=1 fixed" --filename pol_r1_combined -i plots/2018-05-22_ztt_polarisation_datacards_mt_et_em_leg1_tt_inclusive/datacards/individual/mt/1031/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_em_leg1_tt_inclusive_m_vis/datacards/individual/mt/1031/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_em_combined/datacards/channel/mt/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2/datacards/channel/mt/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2_m_vis/datacards/channel/mt/higgsCombine.pol_r1.MultiDimFit.mH0.root -C 2 2 2 2 3 3 3 3 4 4 4 4 6 6 6 6 7 7 7 7 --y-lims 0 100 --x-lims -1 1 --labels "#bar{#omega}(#mu)" "" "" "" "#bar{#omega}(a_{1}/#rho/#pi)" "" "" "" "#bar{#Omega}(#mu,a_{1}/#rho/#pi)" "" "" "" "m_{vis}(#mu,#tau_{h})" "" "" "" "m_{vis}(#mu,a_{1}/#rho/#pi)" "" "" "" &

higgsplot.py --no-cache --legend 0.22 0.75 0.9 0.9 --legend-markers LP --legend-cols 4 --x-label "Average Polarisation #LTP_{#tau}#GT" --y-label "Likelihood -2#Deltaln L" -f limit -x pol -y "2*deltaNLL" --tree-draw-options TGraph --analysis-modules LikelihoodScan -m LP L L L --marker-sizes 0.5 --line-styles 1 1 2 3 --formats pdf png --www taupol/likelihood_scans/asimov/mt --title "#mu#tau_{h}, r floating" --filename pol_omegabar_comparison -i plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2/datacards/channel/mt/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2/datacards/individual/mt/1010/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2/datacards/individual/mt/1020/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2/datacards/individual/mt/1030/higgsCombine.pol.MultiDimFit.mH0.root -C 1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 --y-lims 0 100 --x-lims -1 1 --labels "#bar{#omega}(a_{1}/#rho/#pi)" "" "" "" "#bar{#omega}(a_{1})" "" "" "" "#bar{#omega}(#rho)" "" "" "" "#bar{#omega}(#pi)" "" "" "" &

higgsplot.py --no-cache --legend 0.22 0.75 0.9 0.9 --legend-markers LP --legend-cols 4 --x-label "Average Polarisation #LTP_{#tau}#GT" --y-label "Likelihood -2#Deltaln L" -f limit -x pol -y "2*deltaNLL" --tree-draw-options TGraph --analysis-modules LikelihoodScan -m LP L L L --marker-sizes 0.5 --line-styles 1 1 2 3 --formats pdf png --www taupol/likelihood_scans/asimov/mt --title "#mu#tau_{h}, r=1 fixed" --filename pol_r1_omegabar_comparison -i plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2/datacards/channel/mt/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2/datacards/individual/mt/1010/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2/datacards/individual/mt/1020/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2/datacards/individual/mt/1030/higgsCombine.pol_r1.MultiDimFit.mH0.root -C 1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 --y-lims 0 100 --x-lims -1 1 --labels "#bar{#omega}(a_{1}/#rho/#pi)" "" "" "" "#bar{#omega}(a_{1})" "" "" "" "#bar{#omega}(#rho)" "" "" "" "#bar{#omega}(#pi)" "" "" "" &

higgsplot.py --no-cache --legend 0.22 0.75 0.9 0.9 --legend-markers LP --legend-cols 4 --x-label "Average Polarisation #LTP_{#tau}#GT" --y-label "Likelihood -2#Deltaln L" -f limit -x pol -y "2*deltaNLL" --tree-draw-options TGraph --analysis-modules LikelihoodScan -m LP L L L --marker-sizes 0.5 --line-styles 1 1 2 3 --formats pdf png --www taupol/likelihood_scans/asimov/mt --title "#mu#tau_{h}, r floating" --filename pol_combinedomegabar_comparison -i plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_em_combined/datacards/channel/mt/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_em_combined/datacards/individual/mt/1050/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_em_combined/datacards/individual/mt/1040/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_em_combined/datacards/individual/mt/1060/higgsCombine.pol.MultiDimFit.mH0.root -C 1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 --y-lims 0 100 --x-lims -1 1 --labels "#bar{#Omega}(#mu,a_{1}/#rho/#pi)" "" "" "" "#bar{#Omega}(#mu,a_{1})" "" "" "" "#bar{#Omega}(#mu,#rho)" "" "" "" "#bar{#Omega}(#mu,#pi)" "" "" "" &

higgsplot.py --no-cache --legend 0.22 0.75 0.9 0.9 --legend-markers LP --legend-cols 4 --x-label "Average Polarisation #LTP_{#tau}#GT" --y-label "Likelihood -2#Deltaln L" -f limit -x pol -y "2*deltaNLL" --tree-draw-options TGraph --analysis-modules LikelihoodScan -m LP L L L --marker-sizes 0.5 --line-styles 1 1 2 3 --formats pdf png --www taupol/likelihood_scans/asimov/mt --title "#mu#tau_{h}, r=1 fixed" --filename pol_r1_combinedomegabar_comparison -i plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_em_combined/datacards/channel/mt/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_em_combined/datacards/individual/mt/1050/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_em_combined/datacards/individual/mt/1040/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_em_combined/datacards/individual/mt/1060/higgsCombine.pol_r1.MultiDimFit.mH0.root -C 1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 --y-lims 0 100 --x-lims -1 1 --labels "#bar{#Omega}(#mu,a_{1}/#rho/#pi)" "" "" "" "#bar{#Omega}(#mu,a_{1})" "" "" "" "#bar{#Omega}(#mu,#rho)" "" "" "" "#bar{#Omega}(#mu,#pi)" "" "" "" &

higgsplot.py --no-cache --legend 0.22 0.75 0.9 0.9 --legend-markers LP --legend-cols 4 --x-label "Average Polarisation #LTP_{#tau}#GT" --y-label "Likelihood -2#Deltaln L" -f limit -x pol -y "2*deltaNLL" --tree-draw-options TGraph --analysis-modules LikelihoodScan -m LP L L L --marker-sizes 0.5 --line-styles 1 1 2 3 --formats pdf png --www taupol/likelihood_scans/asimov/mt --title "#mu#tau_{h}, r floating" --filename pol_combinedmvis_comparison -i plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2_m_vis/datacards/channel/mt/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2_m_vis/datacards/individual/mt/1010/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2_m_vis/datacards/individual/mt/1020/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2_m_vis/datacards/individual/mt/1030/higgsCombine.pol.MultiDimFit.mH0.root -C 1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 --y-lims 0 100 --x-lims -1 1 --labels "m_{vis}(#mu,a_{1}/#rho/#pi)" "" "" "" "m_{vis}(#mu,a_{1})" "" "" "" "m_{vis}(#mu,#rho)" "" "" "" "m_{vis}(#mu,#pi)" "" "" "" &

higgsplot.py --no-cache --legend 0.22 0.75 0.9 0.9 --legend-markers LP --legend-cols 4 --x-label "Average Polarisation #LTP_{#tau}#GT" --y-label "Likelihood -2#Deltaln L" -f limit -x pol -y "2*deltaNLL" --tree-draw-options TGraph --analysis-modules LikelihoodScan -m LP L L L --marker-sizes 0.5 --line-styles 1 1 2 3 --formats pdf png --www taupol/likelihood_scans/asimov/mt --title "#mu#tau_{h}, r=1 fixed" --filename pol_r1_combinedmvis_comparison -i plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2_m_vis/datacards/channel/mt/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2_m_vis/datacards/individual/mt/1010/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2_m_vis/datacards/individual/mt/1020/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2_m_vis/datacards/individual/mt/1030/higgsCombine.pol_r1.MultiDimFit.mH0.root -C 1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 --y-lims 0 100 --x-lims -1 1 --labels "m_{vis}(#mu,a_{1}/#rho/#pi)" "" "" "" "m_{vis}(#mu,a_{1})" "" "" "" "m_{vis}(#mu,#rho)" "" "" "" "m_{vis}(#mu,#pi)" "" "" "" &

## zoomed

higgsplot.py --no-cache --legend 0.22 0.7 0.9 0.9 --legend-markers LP --legend-cols 3 --x-label "Average Polarisation #LTP_{#tau}#GT" --y-label "Likelihood -2#Deltaln L" -f limit -x pol -y "2*deltaNLL" --tree-draw-options TGraph --analysis-modules LikelihoodScan -m LP L L L --marker-sizes 0.5 --line-styles 1 1 2 3 --formats pdf png --www taupol/likelihood_scans/asimov/mt --title "#mu#tau_{h}, r floating" --filename pol_combined_zoom -i plots/2018-05-22_ztt_polarisation_datacards_mt_et_em_leg1_tt_inclusive/datacards/individual/mt/1031/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_em_leg1_tt_inclusive_m_vis/datacards/individual/mt/1031/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_em_combined/datacards/channel/mt/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2/datacards/channel/mt/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2_m_vis/datacards/channel/mt/higgsCombine.pol.MultiDimFit.mH0.root -C 2 2 2 2 3 3 3 3 4 4 4 4 6 6 6 6 7 7 7 7 --y-lims 0 10 --x-lims -0.3 0.0 --labels "#bar{#omega}(#mu)" "" "" "" "#bar{#omega}(a_{1}/#rho/#pi)" "" "" "" "#bar{#Omega}(#mu,a_{1}/#rho/#pi)" "" "" "" "m_{vis}(#mu,#tau_{h})" "" "" "" "m_{vis}(#mu,a_{1}/#rho/#pi)" "" "" "" &

higgsplot.py --no-cache --legend 0.22 0.7 0.9 0.9 --legend-markers LP --legend-cols 3 --x-label "Average Polarisation #LTP_{#tau}#GT" --y-label "Likelihood -2#Deltaln L" -f limit -x pol -y "2*deltaNLL" --tree-draw-options TGraph --analysis-modules LikelihoodScan -m LP L L L --marker-sizes 0.5 --line-styles 1 1 2 3 --formats pdf png --www taupol/likelihood_scans/asimov/mt --title "#mu#tau_{h}, r=1 fixed" --filename pol_r1_combined_zoom -i plots/2018-05-22_ztt_polarisation_datacards_mt_et_em_leg1_tt_inclusive/datacards/individual/mt/1031/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_em_leg1_tt_inclusive_m_vis/datacards/individual/mt/1031/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_em_combined/datacards/channel/mt/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2/datacards/channel/mt/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2_m_vis/datacards/channel/mt/higgsCombine.pol_r1.MultiDimFit.mH0.root -C 2 2 2 2 3 3 3 3 4 4 4 4 6 6 6 6 7 7 7 7 --y-lims 0 10 --x-lims -0.3 0.0 --labels "#bar{#omega}(#mu)" "" "" "" "#bar{#omega}(a_{1}/#rho/#pi)" "" "" "" "#bar{#Omega}(#mu,a_{1}/#rho/#pi)" "" "" "" "m_{vis}(#mu,#tau_{h})" "" "" "" "m_{vis}(#mu,a_{1}/#rho/#pi)" "" "" "" &

higgsplot.py --no-cache --legend 0.22 0.75 0.9 0.9 --legend-markers LP --legend-cols 4 --x-label "Average Polarisation #LTP_{#tau}#GT" --y-label "Likelihood -2#Deltaln L" -f limit -x pol -y "2*deltaNLL" --tree-draw-options TGraph --analysis-modules LikelihoodScan -m LP L L L --marker-sizes 0.5 --line-styles 1 1 2 3 --formats pdf png --www taupol/likelihood_scans/asimov/mt --title "#mu#tau_{h}, r floating" --filename pol_omegabar_comparison_zoom -i plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2/datacards/channel/mt/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2/datacards/individual/mt/1010/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2/datacards/individual/mt/1020/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2/datacards/individual/mt/1030/higgsCombine.pol.MultiDimFit.mH0.root -C 1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 --y-lims 0 10 --x-lims -0.3 0.0 --labels "#bar{#omega}(a_{1}/#rho/#pi)" "" "" "" "#bar{#omega}(a_{1})" "" "" "" "#bar{#omega}(#rho)" "" "" "" "#bar{#omega}(#pi)" "" "" "" &

higgsplot.py --no-cache --legend 0.22 0.75 0.9 0.9 --legend-markers LP --legend-cols 4 --x-label "Average Polarisation #LTP_{#tau}#GT" --y-label "Likelihood -2#Deltaln L" -f limit -x pol -y "2*deltaNLL" --tree-draw-options TGraph --analysis-modules LikelihoodScan -m LP L L L --marker-sizes 0.5 --line-styles 1 1 2 3 --formats pdf png --www taupol/likelihood_scans/asimov/mt --title "#mu#tau_{h}, r=1 fixed" --filename pol_r1_omegabar_comparison_zoom -i plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2/datacards/channel/mt/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2/datacards/individual/mt/1010/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2/datacards/individual/mt/1020/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2/datacards/individual/mt/1030/higgsCombine.pol_r1.MultiDimFit.mH0.root -C 1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 --y-lims 0 10 --x-lims -0.3 0.0 --labels "#bar{#omega}(a_{1}/#rho/#pi)" "" "" "" "#bar{#omega}(a_{1})" "" "" "" "#bar{#omega}(#rho)" "" "" "" "#bar{#omega}(#pi)" "" "" "" &

higgsplot.py --no-cache --legend 0.22 0.75 0.9 0.9 --legend-markers LP --legend-cols 4 --x-label "Average Polarisation #LTP_{#tau}#GT" --y-label "Likelihood -2#Deltaln L" -f limit -x pol -y "2*deltaNLL" --tree-draw-options TGraph --analysis-modules LikelihoodScan -m LP L L L --marker-sizes 0.5 --line-styles 1 1 2 3 --formats pdf png --www taupol/likelihood_scans/asimov/mt --title "#mu#tau_{h}, r floating" --filename pol_combinedomegabar_comparison_zoom -i plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_em_combined/datacards/channel/mt/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_em_combined/datacards/individual/mt/1050/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_em_combined/datacards/individual/mt/1040/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_em_combined/datacards/individual/mt/1060/higgsCombine.pol.MultiDimFit.mH0.root -C 1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 --y-lims 0 10 --x-lims -0.3 0.0 --labels "#bar{#Omega}(#mu,a_{1}/#rho/#pi)" "" "" "" "#bar{#Omega}(#mu,a_{1})" "" "" "" "#bar{#Omega}(#mu,#rho)" "" "" "" "#bar{#Omega}(#mu,#pi)" "" "" "" &

higgsplot.py --no-cache --legend 0.22 0.75 0.9 0.9 --legend-markers LP --legend-cols 4 --x-label "Average Polarisation #LTP_{#tau}#GT" --y-label "Likelihood -2#Deltaln L" -f limit -x pol -y "2*deltaNLL" --tree-draw-options TGraph --analysis-modules LikelihoodScan -m LP L L L --marker-sizes 0.5 --line-styles 1 1 2 3 --formats pdf png --www taupol/likelihood_scans/asimov/mt --title "#mu#tau_{h}, r=1 fixed" --filename pol_r1_combinedomegabar_comparison_zoom -i plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_em_combined/datacards/channel/mt/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_em_combined/datacards/individual/mt/1050/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_em_combined/datacards/individual/mt/1040/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_em_combined/datacards/individual/mt/1060/higgsCombine.pol_r1.MultiDimFit.mH0.root -C 1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 --y-lims 0 10 --x-lims -0.3 0.0 --labels "#bar{#Omega}(#mu,a_{1}/#rho/#pi)" "" "" "" "#bar{#Omega}(#mu,a_{1})" "" "" "" "#bar{#Omega}(#mu,#rho)" "" "" "" "#bar{#Omega}(#mu,#pi)" "" "" "" &

higgsplot.py --no-cache --legend 0.22 0.75 0.9 0.9 --legend-markers LP --legend-cols 4 --x-label "Average Polarisation #LTP_{#tau}#GT" --y-label "Likelihood -2#Deltaln L" -f limit -x pol -y "2*deltaNLL" --tree-draw-options TGraph --analysis-modules LikelihoodScan -m LP L L L --marker-sizes 0.5 --line-styles 1 1 2 3 --formats pdf png --www taupol/likelihood_scans/asimov/mt --title "#mu#tau_{h}, r floating" --filename pol_combinedmvis_comparison_zoom -i plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2_m_vis/datacards/channel/mt/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2_m_vis/datacards/individual/mt/1010/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2_m_vis/datacards/individual/mt/1020/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2_m_vis/datacards/individual/mt/1030/higgsCombine.pol.MultiDimFit.mH0.root -C 1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 --y-lims 0 10 --x-lims -0.3 0.0 --labels "m_{vis}(#mu,a_{1}/#rho/#pi)" "" "" "" "m_{vis}(#mu,a_{1})" "" "" "" "m_{vis}(#mu,#rho)" "" "" "" "m_{vis}(#mu,#pi)" "" "" "" &

higgsplot.py --no-cache --legend 0.22 0.75 0.9 0.9 --legend-markers LP --legend-cols 4 --x-label "Average Polarisation #LTP_{#tau}#GT" --y-label "Likelihood -2#Deltaln L" -f limit -x pol -y "2*deltaNLL" --tree-draw-options TGraph --analysis-modules LikelihoodScan -m LP L L L --marker-sizes 0.5 --line-styles 1 1 2 3 --formats pdf png --www taupol/likelihood_scans/asimov/mt --title "#mu#tau_{h}, r=1 fixed" --filename pol_r1_combinedmvis_comparison_zoom -i plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2_m_vis/datacards/channel/mt/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2_m_vis/datacards/individual/mt/1010/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2_m_vis/datacards/individual/mt/1020/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2_m_vis/datacards/individual/mt/1030/higgsCombine.pol_r1.MultiDimFit.mH0.root -C 1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 --y-lims 0 10 --x-lims -0.3 0.0 --labels "m_{vis}(#mu,a_{1}/#rho/#pi)" "" "" "" "m_{vis}(#mu,a_{1})" "" "" "" "m_{vis}(#mu,#rho)" "" "" "" "m_{vis}(#mu,#pi)" "" "" "" &



# ET

higgsplot.py --no-cache --legend 0.22 0.7 0.9 0.9 --legend-markers LP --legend-cols 3 --x-label "Average Polarisation #LTP_{#tau}#GT" --y-label "Likelihood -2#Deltaln L" -f limit -x pol -y "2*deltaNLL" --tree-draw-options TGraph --analysis-modules LikelihoodScan -m LP L L L --marker-sizes 0.5 --line-styles 1 1 2 3 --formats pdf png --www taupol/likelihood_scans/asimov/et --title "e#tau_{h}, r floating" --filename pol_combined -i plots/2018-05-22_ztt_polarisation_datacards_mt_et_em_leg1_tt_inclusive/datacards/individual/et/1031/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_em_leg1_tt_inclusive_m_vis/datacards/individual/et/1031/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_em_combined/datacards/channel/et/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2/datacards/channel/et/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2_m_vis/datacards/channel/et/higgsCombine.pol.MultiDimFit.mH0.root -C 2 2 2 2 3 3 3 3 4 4 4 4 6 6 6 6 7 7 7 7 --y-lims 0 100 --x-lims -1 1 --labels "#bar{#omega}(e)" "" "" "" "#bar{#omega}(a_{1}/#rho/#pi)" "" "" "" "#bar{#Omega}(e,a_{1}/#rho/#pi)" "" "" "" "m_{vis}(e,#tau_{h})" "" "" "" "m_{vis}(e,a_{1}/#rho/#pi)" "" "" "" &

higgsplot.py --no-cache --legend 0.22 0.7 0.9 0.9 --legend-markers LP --legend-cols 3 --x-label "Average Polarisation #LTP_{#tau}#GT" --y-label "Likelihood -2#Deltaln L" -f limit -x pol -y "2*deltaNLL" --tree-draw-options TGraph --analysis-modules LikelihoodScan -m LP L L L --marker-sizes 0.5 --line-styles 1 1 2 3 --formats pdf png --www taupol/likelihood_scans/asimov/et --title "e#tau_{h}, r=1 fixed" --filename pol_r1_combined -i plots/2018-05-22_ztt_polarisation_datacards_mt_et_em_leg1_tt_inclusive/datacards/individual/et/1031/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_em_leg1_tt_inclusive_m_vis/datacards/individual/et/1031/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_em_combined/datacards/channel/et/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2/datacards/channel/et/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2_m_vis/datacards/channel/et/higgsCombine.pol_r1.MultiDimFit.mH0.root -C 2 2 2 2 3 3 3 3 4 4 4 4 6 6 6 6 7 7 7 7 --y-lims 0 100 --x-lims -1 1 --labels "#bar{#omega}(e)" "" "" "" "#bar{#omega}(a_{1}/#rho/#pi)" "" "" "" "#bar{#Omega}(e,a_{1}/#rho/#pi)" "" "" "" "m_{vis}(e,#tau_{h})" "" "" "" "m_{vis}(e,a_{1}/#rho/#pi)" "" "" "" &

higgsplot.py --no-cache --legend 0.22 0.75 0.9 0.9 --legend-markers LP --legend-cols 4 --x-label "Average Polarisation #LTP_{#tau}#GT" --y-label "Likelihood -2#Deltaln L" -f limit -x pol -y "2*deltaNLL" --tree-draw-options TGraph --analysis-modules LikelihoodScan -m LP L L L --marker-sizes 0.5 --line-styles 1 1 2 3 --formats pdf png --www taupol/likelihood_scans/asimov/et --title "e#tau_{h}, r floating" --filename pol_omegabar_comparison -i plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2/datacards/channel/et/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2/datacards/individual/et/1010/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2/datacards/individual/et/1020/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2/datacards/individual/et/1030/higgsCombine.pol.MultiDimFit.mH0.root -C 1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 --y-lims 0 100 --x-lims -1 1 --labels "#bar{#omega}(a_{1}/#rho/#pi)" "" "" "" "#bar{#omega}(a_{1})" "" "" "" "#bar{#omega}(#rho)" "" "" "" "#bar{#omega}(#pi)" "" "" "" &

higgsplot.py --no-cache --legend 0.22 0.75 0.9 0.9 --legend-markers LP --legend-cols 4 --x-label "Average Polarisation #LTP_{#tau}#GT" --y-label "Likelihood -2#Deltaln L" -f limit -x pol -y "2*deltaNLL" --tree-draw-options TGraph --analysis-modules LikelihoodScan -m LP L L L --marker-sizes 0.5 --line-styles 1 1 2 3 --formats pdf png --www taupol/likelihood_scans/asimov/et --title "e#tau_{h}, r=1 fixed" --filename pol_r1_omegabar_comparison -i plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2/datacards/channel/et/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2/datacards/individual/et/1010/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2/datacards/individual/et/1020/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2/datacards/individual/et/1030/higgsCombine.pol_r1.MultiDimFit.mH0.root -C 1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 --y-lims 0 100 --x-lims -1 1 --labels "#bar{#omega}(a_{1}/#rho/#pi)" "" "" "" "#bar{#omega}(a_{1})" "" "" "" "#bar{#omega}(#rho)" "" "" "" "#bar{#omega}(#pi)" "" "" "" &

higgsplot.py --no-cache --legend 0.22 0.75 0.9 0.9 --legend-markers LP --legend-cols 4 --x-label "Average Polarisation #LTP_{#tau}#GT" --y-label "Likelihood -2#Deltaln L" -f limit -x pol -y "2*deltaNLL" --tree-draw-options TGraph --analysis-modules LikelihoodScan -m LP L L L --marker-sizes 0.5 --line-styles 1 1 2 3 --formats pdf png --www taupol/likelihood_scans/asimov/et --title "e#tau_{h}, r floating" --filename pol_combinedomegabar_comparison -i plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_em_combined/datacards/channel/et/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_em_combined/datacards/individual/et/1050/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_em_combined/datacards/individual/et/1040/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_em_combined/datacards/individual/et/1060/higgsCombine.pol.MultiDimFit.mH0.root -C 1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 --y-lims 0 100 --x-lims -1 1 --labels "#bar{#Omega}(e,a_{1}/#rho/#pi)" "" "" "" "#bar{#Omega}(e,a_{1})" "" "" "" "#bar{#Omega}(e,#rho)" "" "" "" "#bar{#Omega}(e,#pi)" "" "" "" &

higgsplot.py --no-cache --legend 0.22 0.75 0.9 0.9 --legend-markers LP --legend-cols 4 --x-label "Average Polarisation #LTP_{#tau}#GT" --y-label "Likelihood -2#Deltaln L" -f limit -x pol -y "2*deltaNLL" --tree-draw-options TGraph --analysis-modules LikelihoodScan -m LP L L L --marker-sizes 0.5 --line-styles 1 1 2 3 --formats pdf png --www taupol/likelihood_scans/asimov/et --title "e#tau_{h}, r=1 fixed" --filename pol_r1_combinedomegabar_comparison -i plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_em_combined/datacards/channel/et/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_em_combined/datacards/individual/et/1050/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_em_combined/datacards/individual/et/1040/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_em_combined/datacards/individual/et/1060/higgsCombine.pol_r1.MultiDimFit.mH0.root -C 1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 --y-lims 0 100 --x-lims -1 1 --labels "#bar{#Omega}(e,a_{1}/#rho/#pi)" "" "" "" "#bar{#Omega}(e,a_{1})" "" "" "" "#bar{#Omega}(e,#rho)" "" "" "" "#bar{#Omega}(e,#pi)" "" "" "" &

higgsplot.py --no-cache --legend 0.22 0.75 0.9 0.9 --legend-markers LP --legend-cols 4 --x-label "Average Polarisation #LTP_{#tau}#GT" --y-label "Likelihood -2#Deltaln L" -f limit -x pol -y "2*deltaNLL" --tree-draw-options TGraph --analysis-modules LikelihoodScan -m LP L L L --marker-sizes 0.5 --line-styles 1 1 2 3 --formats pdf png --www taupol/likelihood_scans/asimov/et --title "e#tau_{h}, r floating" --filename pol_combinedmvis_comparison -i plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2_m_vis/datacards/channel/et/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2_m_vis/datacards/individual/et/1010/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2_m_vis/datacards/individual/et/1020/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2_m_vis/datacards/individual/et/1030/higgsCombine.pol.MultiDimFit.mH0.root -C 1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 --y-lims 0 100 --x-lims -1 1 --labels "m_{vis}(e,a_{1}/#rho/#pi)" "" "" "" "m_{vis}(e,a_{1})" "" "" "" "m_{vis}(e,#rho)" "" "" "" "m_{vis}(e,#pi)" "" "" "" &

higgsplot.py --no-cache --legend 0.22 0.75 0.9 0.9 --legend-markers LP --legend-cols 4 --x-label "Average Polarisation #LTP_{#tau}#GT" --y-label "Likelihood -2#Deltaln L" -f limit -x pol -y "2*deltaNLL" --tree-draw-options TGraph --analysis-modules LikelihoodScan -m LP L L L --marker-sizes 0.5 --line-styles 1 1 2 3 --formats pdf png --www taupol/likelihood_scans/asimov/et --title "e#tau_{h}, r=1 fixed" --filename pol_r1_combinedmvis_comparison -i plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2_m_vis/datacards/channel/et/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2_m_vis/datacards/individual/et/1010/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2_m_vis/datacards/individual/et/1020/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2_m_vis/datacards/individual/et/1030/higgsCombine.pol_r1.MultiDimFit.mH0.root -C 1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 --y-lims 0 100 --x-lims -1 1 --labels "m_{vis}(e,a_{1}/#rho/#pi)" "" "" "" "m_{vis}(e,a_{1})" "" "" "" "m_{vis}(e,#rho)" "" "" "" "m_{vis}(e,#pi)" "" "" "" &

## zoomed

higgsplot.py --no-cache --legend 0.22 0.7 0.9 0.9 --legend-markers LP --legend-cols 3 --x-label "Average Polarisation #LTP_{#tau}#GT" --y-label "Likelihood -2#Deltaln L" -f limit -x pol -y "2*deltaNLL" --tree-draw-options TGraph --analysis-modules LikelihoodScan -m LP L L L --marker-sizes 0.5 --line-styles 1 1 2 3 --formats pdf png --www taupol/likelihood_scans/asimov/et --title "e#tau_{h}, r floating" --filename pol_combined_zoom -i plots/2018-05-22_ztt_polarisation_datacards_mt_et_em_leg1_tt_inclusive/datacards/individual/et/1031/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_em_leg1_tt_inclusive_m_vis/datacards/individual/et/1031/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_em_combined/datacards/channel/et/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2/datacards/channel/et/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2_m_vis/datacards/channel/et/higgsCombine.pol.MultiDimFit.mH0.root -C 2 2 2 2 3 3 3 3 4 4 4 4 6 6 6 6 7 7 7 7 --y-lims 0 10 --x-lims -0.3 0.0 --labels "#bar{#omega}(e)" "" "" "" "#bar{#omega}(a_{1}/#rho/#pi)" "" "" "" "#bar{#Omega}(e,a_{1}/#rho/#pi)" "" "" "" "m_{vis}(e,#tau_{h})" "" "" "" "m_{vis}(e,a_{1}/#rho/#pi)" "" "" "" &

higgsplot.py --no-cache --legend 0.22 0.7 0.9 0.9 --legend-markers LP --legend-cols 3 --x-label "Average Polarisation #LTP_{#tau}#GT" --y-label "Likelihood -2#Deltaln L" -f limit -x pol -y "2*deltaNLL" --tree-draw-options TGraph --analysis-modules LikelihoodScan -m LP L L L --marker-sizes 0.5 --line-styles 1 1 2 3 --formats pdf png --www taupol/likelihood_scans/asimov/et --title "e#tau_{h}, r=1 fixed" --filename pol_r1_combined_zoom -i plots/2018-05-22_ztt_polarisation_datacards_mt_et_em_leg1_tt_inclusive/datacards/individual/et/1031/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_em_leg1_tt_inclusive_m_vis/datacards/individual/et/1031/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_em_combined/datacards/channel/et/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2/datacards/channel/et/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2_m_vis/datacards/channel/et/higgsCombine.pol_r1.MultiDimFit.mH0.root -C 2 2 2 2 3 3 3 3 4 4 4 4 6 6 6 6 7 7 7 7 --y-lims 0 10 --x-lims -0.3 0.0 --labels "#bar{#omega}(e)" "" "" "" "#bar{#omega}(a_{1}/#rho/#pi)" "" "" "" "#bar{#Omega}(e,a_{1}/#rho/#pi)" "" "" "" "m_{vis}(e,#tau_{h})" "" "" "" "m_{vis}(e,a_{1}/#rho/#pi)" "" "" "" &

higgsplot.py --no-cache --legend 0.22 0.75 0.9 0.9 --legend-markers LP --legend-cols 4 --x-label "Average Polarisation #LTP_{#tau}#GT" --y-label "Likelihood -2#Deltaln L" -f limit -x pol -y "2*deltaNLL" --tree-draw-options TGraph --analysis-modules LikelihoodScan -m LP L L L --marker-sizes 0.5 --line-styles 1 1 2 3 --formats pdf png --www taupol/likelihood_scans/asimov/et --title "e#tau_{h}, r floating" --filename pol_omegabar_comparison_zoom -i plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2/datacards/channel/et/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2/datacards/individual/et/1010/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2/datacards/individual/et/1020/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2/datacards/individual/et/1030/higgsCombine.pol.MultiDimFit.mH0.root -C 1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 --y-lims 0 10 --x-lims -0.3 0.0 --labels "#bar{#omega}(a_{1}/#rho/#pi)" "" "" "" "#bar{#omega}(a_{1})" "" "" "" "#bar{#omega}(#rho)" "" "" "" "#bar{#omega}(#pi)" "" "" "" &

higgsplot.py --no-cache --legend 0.22 0.75 0.9 0.9 --legend-markers LP --legend-cols 4 --x-label "Average Polarisation #LTP_{#tau}#GT" --y-label "Likelihood -2#Deltaln L" -f limit -x pol -y "2*deltaNLL" --tree-draw-options TGraph --analysis-modules LikelihoodScan -m LP L L L --marker-sizes 0.5 --line-styles 1 1 2 3 --formats pdf png --www taupol/likelihood_scans/asimov/et --title "e#tau_{h}, r=1 fixed" --filename pol_r1_omegabar_comparison_zoom -i plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2/datacards/channel/et/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2/datacards/individual/et/1010/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2/datacards/individual/et/1020/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2/datacards/individual/et/1030/higgsCombine.pol_r1.MultiDimFit.mH0.root -C 1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 --y-lims 0 10 --x-lims -0.3 0.0 --labels "#bar{#omega}(a_{1}/#rho/#pi)" "" "" "" "#bar{#omega}(a_{1})" "" "" "" "#bar{#omega}(#rho)" "" "" "" "#bar{#omega}(#pi)" "" "" "" &

higgsplot.py --no-cache --legend 0.22 0.75 0.9 0.9 --legend-markers LP --legend-cols 4 --x-label "Average Polarisation #LTP_{#tau}#GT" --y-label "Likelihood -2#Deltaln L" -f limit -x pol -y "2*deltaNLL" --tree-draw-options TGraph --analysis-modules LikelihoodScan -m LP L L L --marker-sizes 0.5 --line-styles 1 1 2 3 --formats pdf png --www taupol/likelihood_scans/asimov/et --title "e#tau_{h}, r floating" --filename pol_combinedomegabar_comparison_zoom -i plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_em_combined/datacards/channel/et/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_em_combined/datacards/individual/et/1050/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_em_combined/datacards/individual/et/1040/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_em_combined/datacards/individual/et/1060/higgsCombine.pol.MultiDimFit.mH0.root -C 1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 --y-lims 0 10 --x-lims -0.3 0.0 --labels "#bar{#Omega}(e,a_{1}/#rho/#pi)" "" "" "" "#bar{#Omega}(e,a_{1})" "" "" "" "#bar{#Omega}(e,#rho)" "" "" "" "#bar{#Omega}(e,#pi)" "" "" "" &

higgsplot.py --no-cache --legend 0.22 0.75 0.9 0.9 --legend-markers LP --legend-cols 4 --x-label "Average Polarisation #LTP_{#tau}#GT" --y-label "Likelihood -2#Deltaln L" -f limit -x pol -y "2*deltaNLL" --tree-draw-options TGraph --analysis-modules LikelihoodScan -m LP L L L --marker-sizes 0.5 --line-styles 1 1 2 3 --formats pdf png --www taupol/likelihood_scans/asimov/et --title "e#tau_{h}, r=1 fixed" --filename pol_r1_combinedomegabar_comparison_zoom -i plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_em_combined/datacards/channel/et/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_em_combined/datacards/individual/et/1050/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_em_combined/datacards/individual/et/1040/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_em_combined/datacards/individual/et/1060/higgsCombine.pol_r1.MultiDimFit.mH0.root -C 1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 --y-lims 0 10 --x-lims -0.3 0.0 --labels "#bar{#Omega}(e,a_{1}/#rho/#pi)" "" "" "" "#bar{#Omega}(e,a_{1})" "" "" "" "#bar{#Omega}(e,#rho)" "" "" "" "#bar{#Omega}(e,#pi)" "" "" "" &

higgsplot.py --no-cache --legend 0.22 0.75 0.9 0.9 --legend-markers LP --legend-cols 4 --x-label "Average Polarisation #LTP_{#tau}#GT" --y-label "Likelihood -2#Deltaln L" -f limit -x pol -y "2*deltaNLL" --tree-draw-options TGraph --analysis-modules LikelihoodScan -m LP L L L --marker-sizes 0.5 --line-styles 1 1 2 3 --formats pdf png --www taupol/likelihood_scans/asimov/et --title "e#tau_{h}, r floating" --filename pol_combinedmvis_comparison_zoom -i plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2_m_vis/datacards/channel/et/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2_m_vis/datacards/individual/et/1010/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2_m_vis/datacards/individual/et/1020/higgsCombine.pol.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2_m_vis/datacards/individual/et/1030/higgsCombine.pol.MultiDimFit.mH0.root -C 1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 --y-lims 0 10 --x-lims -0.3 0.0 --labels "m_{vis}(e,a_{1}/#rho/#pi)" "" "" "" "m_{vis}(e,a_{1})" "" "" "" "m_{vis}(e,#rho)" "" "" "" "m_{vis}(e,#pi)" "" "" "" &

higgsplot.py --no-cache --legend 0.22 0.75 0.9 0.9 --legend-markers LP --legend-cols 4 --x-label "Average Polarisation #LTP_{#tau}#GT" --y-label "Likelihood -2#Deltaln L" -f limit -x pol -y "2*deltaNLL" --tree-draw-options TGraph --analysis-modules LikelihoodScan -m LP L L L --marker-sizes 0.5 --line-styles 1 1 2 3 --formats pdf png --www taupol/likelihood_scans/asimov/et --title "e#tau_{h}, r=1 fixed" --filename pol_r1_combinedmvis_comparison_zoom -i plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2_m_vis/datacards/channel/et/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2_m_vis/datacards/individual/et/1010/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2_m_vis/datacards/individual/et/1020/higgsCombine.pol_r1.MultiDimFit.mH0.root plots/2018-05-22_ztt_polarisation_datacards_mt_et_tt_singletau_em_leg2_m_vis/datacards/individual/et/1030/higgsCombine.pol_r1.MultiDimFit.mH0.root -C 1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 --y-lims 0 10 --x-lims -0.3 0.0 --labels "m_{vis}(e,a_{1}/#rho/#pi)" "" "" "" "m_{vis}(e,a_{1})" "" "" "" "m_{vis}(e,#rho)" "" "" "" "m_{vis}(e,#pi)" "" "" "" &

